### ISSUE TITLE
Enhancement Suggestions

### ISSUE THREAD

**Issue by JT252** [automateyournetwork/ACEye#131]
John,

Great job so far with this project. I have not found a bug yet, but I do have the following enhancement suggestions:

1. I would like to see a way that I can run aceye for something specific instead of probing the entire fabric. Example; I would like to run aceye to just probe my interfaces for a specific leaf switch so that an admin can quickly assign an available port.
2. I would like to have the ability to modify the output to something that will make sense to my organization. Example; When I look at the output for physical interfaces I see a lot of great information that I will probably never use. Something that would make sense to me is something like:
3.
Port-ID|Port-Description|Usage (usage so that I can see which ports are blacklisted)

Thanks for all of the great work with this project and Happy New Year to you and your family.

John T...

**Comment by automateyournetwork** [comment]
Thanks for the feedback and interest!

1) As of right now it probes all APIs from a list; what you could do is
fork / clone the repo and customize the list for the APIs you are
interested in (instead of running aceye from pip you could run python
aceye.py with your customized API list)
2) Similarly as of right now yes I include all available fields - 2 options
- clone / fork the repo and modify the jinja2 templates *or* you could use
the HTML datatable output and use the option to select columns so the
output in the HTML table is only the columns you are interested in

Happy New Year and thanks for the great feedback - let me know what you
think of the options

John

**Comment by JT252** [comment]
Dude, I prefer that you did it for me, but ok. Question: Can I add the the children of an object to the jinja template?
Example;

Object: l1PhysIf 

 "children": [ # I know this syntax is wrong
                    {
                        "ethpmPhysIf": {
                            "attributes": {
                           "operSt": "down",
                           "operStQual": "admin-down" <- These values tell us that the port is actually down. The Admin State value of l1PhysIf will show all ACI ports up, unless someone blacklisted the ports.

Regards,

John...

**Comment by automateyournetwork** [comment]
I have been thinking about your enhancement and I think what I can do, when
I am back from Cisco Live, is make it where you can pass it an API if you
just want 1 API instead of all of them with a default to all of them

As for the jinja2 for Interfaces I could make a custom second jinja2
template for you for this API again after I get back - this is in the
physical interfaces API right? And you just want those 2 values oper state
and quality in their own files?

Thanks

John

**Comment by JT252** [comment]
Thanks JC,

I'll fork the project and customize it for my use case for now.

Thanks,

JT

**Comment by JT252** [comment]
John,

This worked fine in the ACI simulator, but when I tried it on one of my ACI environments, it failed. When I ran aceye, I noticed that I got a 200 ok for my login and got a 403 for everything else. All the folders where written to my directory, but they were all empty. What are we missing?

Regards,

John T.

**Comment by JT252** [comment]
Yes, so when enter my URL, username, and password, I get a 200 ok on the
following lines I get this:

/api/node/class/fvTenant.json status code 403 (I get the same error for
every module after that)

Note: I am testing this on WSL v1 and ACI version: 4.2.5(L)

John...

**Comment by automateyournetwork** [comment]
Ah my code is all built and tested on v5 + - I am not sure about ACI v4
support sorry

**Comment by JT252** [comment]
You were quick to toss back that hot potato. 😀 I'm going to do some
research to make sure that it's a 4. x issue or if it's a Windows/WSL
issue. This tool has a lot of potential in the enterprise where being on
the latest release is not going to happen anytime soon. I will keep you
posted on my progress or lack thereof.

Regards,

John...

**Comment by automateyournetwork** [comment]
So in theory there are no Linux hooks to this code and you can likely
install Python and run it directly in Windows if you want to eliminate the
WSL issue !

Good luck

John

**Comment by JT252** [comment]
I will also go that route as well.
